import {
  Connection,
  PublicKey,
  TransactionMessage,
  VersionedTransaction,
  ComputeBudgetProgram,
  type TransactionInstruction,
} from '@solana/web3.js';
import { SOLANA_COMMITMENT, COMPUTE_UNIT_LIMIT } from '../config/constants';
import { createLogger } from '../utils/logger';
import type { SwapExecutionParams } from '../types/pool.types';

const logger = createLogger('TransactionBuilder');

/**
 * Assembles a VersionedTransaction with:
 *   1. Compute Budget instruction (priority fee + unit limit)
 *   2. Optional ATA creation instruction
 *   3. Swap instruction(s) from the venue SDK (Raydium / Pump.fun / PumpSwap)
 *
 * Uses V0 transaction format for Address Lookup Tables (ALT) compatibility.
 *
 * @param connection       - Solana RPC connection
 * @param payerPublicKey   - Transaction fee payer (wallet public key)
 * @param swapInstructions - Swap instruction(s) generated by Raydium SDK
 * @param params           - Swap execution parameters (priority fee, etc.)
 * @param ataInstruction   - Optional ATA creation instruction (prepended if present)
 */
export async function buildSwapTransaction(
  connection: Connection,
  payerPublicKey: PublicKey,
  swapInstructions: TransactionInstruction[],
  params: SwapExecutionParams,
  ataInstruction: TransactionInstruction | null = null
): Promise<VersionedTransaction> {
  // Fetch latest blockhash for transaction expiry
  const { blockhash, lastValidBlockHeight } =
    await connection.getLatestBlockhash(SOLANA_COMMITMENT);

  // Assemble instruction sequence
  const instructions: TransactionInstruction[] = [];

  // 1. Compute Budget: set unit limit
  instructions.push(
    ComputeBudgetProgram.setComputeUnitLimit({
      units: COMPUTE_UNIT_LIMIT,
    })
  );

  // 2. Compute Budget: set priority fee
  instructions.push(
    ComputeBudgetProgram.setComputeUnitPrice({
      microLamports: params.priorityFeeMicroLamports,
    })
  );

  // 3. ATA creation (if token account doesn't exist yet)
  if (ataInstruction) {
    instructions.push(ataInstruction);
  }

  // 4. Swap instruction(s) from the venue SDK
  instructions.push(...swapInstructions);

  // Compile into V0 message
  const messageV0 = new TransactionMessage({
    payerKey: payerPublicKey,
    recentBlockhash: blockhash,
    instructions,
  }).compileToV0Message();

  const versionedTx = new VersionedTransaction(messageV0);

  logger.info(
    {
      instructionCount: instructions.length,
      priorityFee: params.priorityFeeMicroLamports,
      blockhash: blockhash.slice(0, 12) + '...',
      lastValidBlockHeight,
    },
    'VersionedTransaction assembled'
  );

  return versionedTx;
}
